export const CustomIdConstant = {
  VINCULATE_GC_MODAL: "VINCULATE_GAMERSCLUB_MODAL",
  VINCULATE_GC_BTN: "VINCULATE_GAMERSCLUB_BUTTON",
  JOIN_QUEUE_BTN: "JOIN_QUEUE_BTN",
  LEAVE_QUEUE_BTN: "LEAVE_QUEUE_BTN",
  VINCULATE_GC_LINK_INPUT: "VINCULATE_GC_LUNK_INPUT"
};